### PR TITLE
Add support for TRAFFICDIRECTOR_MESH_SCOPE_NAME

### PR DESCRIPTION
**Pull request by plasticproxy**
Address https://github.com/envoyproxy/envoy-tools/issues/39

### CODE REVIEW

**Review by Rainton — APPROVED** [review]
LGTM

**Review by adisuissa — COMMENTED** [review]
Overall LGTM, although I'm not very familiar about this tool.

**Comment by plasticproxy** [comment]
bump

**Comment by adisuissa** [comment]
@htuch can you please take a final pass?

**Review by adisuissa — APPROVED** [review]
LGTM

**Review by htuch — APPROVED** [review]

**Comment by htuch** [comment]
@fuqianggao do you know what's up with CI?

**Comment by fuqianggao** [comment]
@plasticproxy re-kick CI?

> @fuqianggao do you know what's up with CI?

@plasticproxy re-kick CI to see if it go through?

**Pull request merged**
